services:
  app:
    container_name: karaoke-app
    build: .
    restart: always
    ports:
      - "5003:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./server/.env:/app/server/.env
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-rootpassword}
      - DB_NAME=${DB_NAME:-karaoke_db}
      - JWT_SECRET=${JWT_SECRET:-29e40324c1f7994bf82017b3debe5bf3ba952c9c297dd5f1776a88cb1e0fd9e467de318cdc604e0cad0af203643763efce9ae1d3bc37c285009e034f3c58f247}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
    depends_on:
      mariadb:
        condition: service_healthy

  # Database Configuration (MariaDB)
  mariadb:
    image: mariadb:latest
    container_name: karaoke_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-karaoke_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-rootpassword}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -p\"$$MYSQL_ROOT_PASSWORD\" -e \"SELECT 1\" >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mariadb_data:
