services:
  app:
    container_name: karaoke-app
    build: .
    restart: always
    ports:
      - "3004:3000"
    volumes:
      - ./server/uploads:/app/server/uploads
      - ./server/.env:/app/server/.env
    environment:
      - NODE_ENV=production
      # Ganti dengan IP NAS Anda (misal: 192.168.1.10) atau nama container jika satu network
      - DB_HOST=${DB_HOST:-192.168.88.3}
      - DB_PORT=${DB_PORT:-3307}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASSWORD:-Bismillah123!}
